version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
      - log-volume:/var/log/mysql
    networks:
      - app-net
 
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    environment:
      INSTANCE_HOST: mysql
      DB_USER: user
      DB_PASS: password
      DB_NAME: db
      DB_PORT: 3306
    networks:
      - app-net

volumes:
  data-volume:
  log-volume:

networks:
  app-net:
    driver: bridge