name: Trigger Cloud Build on branch deletion

on:
  delete:
    branches:
      - '**'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account_id: ${{ secrets.GCP_SA_ID }}

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --region=asia-northeast1 --config cloudbuild_rm_run_tag.yaml -substitutions=_BRANCH_NAME="${{ github.ref }}"